export default {
    //Тексты для многоязычности
    ru: {
        //Client
        //+++Main page
        CL_Main: "Главная",
        CL_News: "Новости",
        CL_Enter: "Войти",
        CL_All_categories: "Все категории",
        CL_Search: "Найти",
        Server_is_not_connected: "Нет соединения с сервером",
        //---Main page

        //+++Common
        Add: "Добавить",
        Remove: "Удалить",
        Search: "Найти",
        GotoPage: "перейти к",
        Content_language: "Язык контента",
        Cancel: "Отмена",
        Save: "Сохранить",
        Adding: "Добавление",
        Saving: "Сохранение",
        Find: "Поиск",
        Title: "Заголовок",
        Author: "Автор",
        Creation_date: "Дата создания",
        Publish_date: "Дата публикации",
        Date: "Дата",
        Published: "Опубликовано",
        Yes: "Да",
        No: "Нет",
        Block: "Заблокировать",
        Registered: "Зарегистрирован",
        User: "Пользователь",
        //---Common

        //+++auth/register forms
        authentication: "Вход",
        registration: "Регистрация",
        rememberme: "Запомнить меня",
        login: "Логин",
        password: "Пароль",
        password_repeat: "Повтор пароля",
        forgot_password: "Забыли пароль",
        enter: "Вход",
        reset_password: "Сбросить пароль",
        email: "E-mail",
        back: "Назад",
        register: "Зарегистрировать",
        first_name: "Имя",
        middle_name: "Фамилия",
        last_name: "Отчество",
        nick: "Псевдоним",
        phone: "Телефон",
        user_icon: "Иконка пользователя",
        site: "Веб-сайт",
        Error_login: "Ошибка авторизации",
        Error_logout: "Ошибка выхода",
        Registration_success: "Регистрация прошла успешно",
        Error_reset_password: "Ошибка сброса пароля",
        Error_registration: "Ошибка регистрации",
        Please_login_again: "Пожалуйста повторите вход",
        Error_fields_fill: "Не все поля заполнены верно",
        Reset_pass_link_sent:
            "Для сброса пароля на ваш e-mail отправлена ссылка",
        //---auth/register forms

        //+++Left panel
        AdminPanel: "Панель управления",
        dashboard: "Главная",
        categories: "Категории",
        posts: "Записи",
        files: "Файлы",
        comments: "Комментарии",
        grids: "Сетки разметки",
        menus: "Меню",
        plugins: "Плагины",
        rss: "Рассылки",
        themes: "Темы",
        widgets: "Виджеты",
        lang: "Языки",
        tools: "Инструменты",
        users: "Пользователи",
        rollup: "Свернуть",
        settings: "Настройки",
        //---Left panel

        //+++Dashboard
        Loading: "Загрузка",
        Publish_posts_by_months: "Публикации записей по месяцам",
        Publish_categories_by_months: "Публикации категорий по месяцам",
        Publish_comments_by_months: "Публикации комментов по месяцам",
        Registration_users_by_months: "Регистрации пользователей по месяцам",
        January: "Январь",
        February: "Февраль",
        March: "Март",
        April: "Апрель",
        May: "Май",
        June: "Июнь",
        July: "Июль",
        August: "Август",
        September: "Сентябрь",
        October: "Октябрь",
        November: "Ноябрь",
        December: "Декабрь",

        Error_load_graphs: "Ошибка загрузки графиков",
        //---Dashboard

        //+++Categories
        Categories_loading: "Категории загружаются",
        Categories_removing: "Категории удаляются",
        Categories_moving: "Категории переносятся",
        Category_name: "Имя категории",
        Category_find: "Поиск категорий",
        Move_down: "Переместить вниз",
        Move_up: "Переместить вверх",
        Edit_category: "Правка категории",
        Remove_category: "Удалить категорию",
        Enter_category: "Войти в категорию",
        Category_saving: "Категория сохраняется",
        Copy_to_All_Languages: "Скопировать во все языки",
        New_category_name: "Имя новой категории",
        Autonumerate: "Автонумерация",
        Out_order: "Порядок вывода",
        by_date: "по датам",
        by_date_back: "по датам обратно",
        by_numbers: "по номерам",
        by_numbers_back: "по номерам обратно",
        Keywords: "Ключевые слова",
        Filed_name: "Имя поля",
        User_fields: "Пользовательские поля",
        Category_adding: "Категория добавляется",
        Add_category: "Добавить категорию",
        Categories_selection: "Выбор категорий",
        Selected: "Выбрано",

        Error_load_categories: "Ошибка получения категорий",
        Category_adding_success: "Категория успешно добавлена",
        Error_category_adding: "Ошибка добавления категории",
        Category_save_success: "Категория успешно сохранена",
        Error_category_saving: "Ошибка сохранения категории",
        Category_remove_success: "Категории успешно удалены",
        Error_category_removing: "Ошибка удаления категорий",
        Categories_not_selected: "Категории не выбраны",
        Error_category_moving: "Ошибка перемещения категорий",
        //---Categories

        //+++Posts
        Posts_loading: "Записи загружаются",
        Post_data_loading: "Загрузка данных записи",
        Posts_removing: "Записи удаляются",
        By_post_header: "По заголовку",
        By_post_text: "По тексту записи",
        Find_post: "Найти запись",
        Edit_post: "Правка записи",
        Remove_post: "Удалить запись",
        Category_not_selected: "Категория не выбрана",
        Select_category_of_posts: "Выбор категории записей",
        Preview: "Предпросмотр",
        Close_preview: "Закрыть предпросмотр",
        Add_post: "Добавление записи",
        Back_to_posts_list: "Назад к списку записей",
        Publish: "Опубликовать",
        Post_title: "Заголовок записи",
        Add_Image: "Добавить изображение",
        Order_By_Hand: "Ручная нумерация",
        Post_Number_Forward_Direction: "Номер записи прямой порядок",
        Post_Number_Backward_Direction: "Номер записи обратный порядок",
        Published: "Опубликовано",
        NotPublished: "Не опубликовано",
        Status: "Статус",
        Category: "Категория",

        Error_load_paginator_data: "Ошибка получения данных записей",
        Error_load_posts: "Ошибка получения записей",
        Posts_remove_success: "Записи успешно удалены",
        Error_remove_posts: "Ошибка удаления записей",
        Posts_not_selected_to_delete: "Не выбрана ниодна запись для удаления",
        Error_load_onepost: "Ошибка загрузки записи",
        Error_save_onepost: "Ошибка сохранения записи",
        Error_find_posts: "Ошибка поиска записей",
        Post_publish_success: "Запись успешно опубликована",
        Post_save_success: "Запись успешно сохранена",
        Error_add_post: "Ошибка добавления записи",
        //---Posts

        //+++Files
        Files_Not_Selected: "Не выбран ни один файл для удаления",
        Select_operations: "Операции выборки",
        Select_All_Visible: "Выбрать все видимые",
        Unselect_All_Visible: "Снять выделение со всех видимых",
        Select_All: "Выбрать всех",
        Unselect_All: "Снять выделение со всех",
        Find_images: "Найти изображения",
        Image_title: "Заголовок изображения",
        Edit_title: "Правка заголовка",
        Image_loading: "Загрузка картинки",
        Image_removing: "Удаление картинок",
        Add_file: "Добавление файла",
        Select_file: "Выбрать файл",
        Image_width: "Ширина изображения",
        Image_height: "Высота изображения",
        Back_to_media_store: "Назад к списку файлов",
        File_does_not_selected: "Файл не выбран",
        Local_file: "Файл с диска",
        FromInternet: "Из интернета",
        FromMediaStore: "Из хранилища",
        Link: "Ссылка",

        Error_load_files: "Ошибка получения списка файлов",
        File_load_success: "Файл успешно загружен",
        Error_load_file: "Ошибка загрузки файла",
        Files_remove_success: "Файлы успешно удалены",
        Error_remove_files: "Ошибка удаления файлов",
        File_save_success: "Файл успешно сохранен",
        Error_save_file: "Ошибка сохранния файла",
        //---Files

        //+++Comments
        Comments_loading: "Загрузка комментариев",
        Comments_user_blocking: "Блокировка пользователей",
        Comments_removing: "Удаление комментариев",
        Comments_saving: "Сохранение комментариев",
        Comments_searching: "Поиск комментариев",
        Comments_user_loading: "Загрузка комментариев пользователя",
        Comments_categories_loading: "Загрузка категорий",
        Filter_By: "Фильтр по",
        All_comments: "Все комментарии",
        By_users: "По пользователям",
        By_posts: "По записям",
        By_Categories: "По категориям",
        No_comments_select_to_block:
            "Не выбран ни один комментарий для блокировки",
        No_comments_select_to_remove:
            "Не выбран ни один комментарий для удаления",
        Part_text_comment: "Фрагмент текста комметария",
        List_view: "Список",
        Tree_view: "Дерево",
        blocked: "заблокирован",
        active: "активен",
        Edit_comment: "Правка комментария",
        Block_user: "Заблокировать пользователя",
        Remove_comment: "Удалить комментарий",
        Find_comment: "Найти комментарий",
        Users_not_selected: "Не выбран ниодин пользователь",
        Comments_delete_of_seleceted_users:
            "Удалить комментарии выделенных пользователей",
        Comments_count: "Коментариев",
        All_comments_of_current_user: "Все комментарии данного пользователя",
        Comments_of_user: "Комментарии пользователя",
        Back_to_comments: "Назад к комментариям",
        Posts_not_selected: "Не выбрана ниодна запись",
        Comments_remove_selected_users:
            "Удалить комментарии выделенных пользователей",
        All_comments_of_current_post: "Все комментарии данной записи",
        Post_comments: "Комментарии к записи",
        Back_to_posts: "Назад к записям",
        Category_not_selected: "Не выбрана ниодна категория",
        Remove_comments: "Удалить комментарии",
        Remove_comments_of_category: "Удалить комментарии категории",
        All_comments_of_current_category: "Все комментарии данной категории",
        Comment: "Комментарий",
        Back_to_categories: "Назад к категориям",

        Error_block_users: "Ошибка блокировки пользователей",
        Error_remove_comments: "Ошибка удаления комментариев",
        Error_save_comments: "Ошибка сохранения комментария",
        Error_find_comments: "Ошибка поиска комментариев",
        Comments_not_selected: "Не выбран ни один комментарий",
        Error_load_comments: "Ошибка загрузки комментариев",
        Users_block_success: "Пользователи успешно заблокированы",
        //---Comments

        //+++RSS
        No_rss_selected: "Рассылки не выбраны",
        Rss_fragment_header: "Фрагмент заголовка ленты",
        Rss_title: "Заголовок ленты",
        Rss_add: "Добавить рассылку",
        Rss_remove: "Удалить рассылки",
        Rss_find: "Найти рассылку",
        Description: "Описание",
        Rss_one_remove: "Удалить рассылку",
        Rss_one_edit: "Правка рассылки",
        Rss_adding: "Добавление рассылки",
        Back_to_rss_list: "Назад к списку рассылок",
        Selected_categories: "Выбранные категории",
        Rss_edit: "Правка рассылки",

        Rss_loading: "Загрузка лент",
        Error_load_rss: "Ошибка получения рассылок",
        Error_remove_rss: "Ошибка удаления лент новостей",
        Error_add_rss: "Ошибка добавления новостной ленты",
        Error_save_rss: "Ошибка сохранения ленты новостей",
        Rss_updating: "Лента сохраняется",
        Rss_removing: "Лента удаляется",
        //---RSS

        //+++Lang
        russian: "Русский",
        english: "Английский",
        german: "Немецкий",
        chinese: "Китайский",
        Russian: "Русский",
        English: "Английский",
        German: "Немецкий",
        Chinese: "Китайский",
        ru: "Русский",
        en: "Английский",
        de: "Немецкий",
        zh: "Китайский",
        Error_load_langs: "Ошибка загрузки языков",
        Error_remove_lang: "Ошибка удаления языков",
        Error_add_lang: "Ошибка добавления языков",

        Min_one_lang_must_be_set: "Минимум один язык является обязательным",
        Langs_loading: "Языки загружаются",
        Langs_adding: "Добавление языков",
        Langs_removing: "Удаление языков",
        UI_Language: "Язык интерфайса",
        Select_User_Interface_Language: "Выбрать язык интерфейса",
        Show_content_language_switcher_on_frontend:
            "Показывать переключатель языков на сайте",
        Content_Languages: "Языки контента",
        All_Languages: "Все языки",
        Find_by: "Найти по",
        By_email: "По e-mail",
        By_first_name: "По имени",
        By_middle_name: "По отчеству",
        By_last_name: "По фамилии",
        By_nick: "По псевдониму",
        By_phone: "По телефону",
        By_site: "По сайту",
        //---Lang

        //+++Users
        Privilege: "Привелегии",
        User_privelege: "Привелегии пользователя",
        Users_privelege: "Привелегии пользователей",
        User_edit: "Правка пользователя",
        User_remove: "Удалить пользователя",
        Back_to_user_list: "Назад к списку пользователей",
        Files_management: "Работа с файлами",
        Admin_access: "Доступ в админку",
        Category_Write: "Запись категорий",
        Category_Read: "Чтение категорий",
        Users_Write: "Запись пользователей",
        Users_Read: "Чтение пользователей",
        Posts_Write: "Запись Постов",
        Posts_Read: "Чтение Постов",
        Priv_Blocked: "Блокировка",
        User_add: "Добавление пользователя",
        Back_to_users: "Назад к списку пользователей",

        Users_loading: "Пользователи загружаются",
        Error_load_users: "Ошибка загрузки пользователей",
        Error_block_users: "Ошибка блокировки пользователей",
        Error_remove_users: "Ошибка удаления пользователей",
        Error_save_privs: "Ошибка сохранения привелегий",
        Error_add_user: "Ошибка добавления пользователя",
        Error_save_user: "Ошибка сохранения пользователя",
        //---Users

        //+++Settings
        SITE_TITLE: "Название сайта",
        KEYWORDS: "Ключевые слова",
        DESCRIPTION: "Описание сайта",
        LANGS_SHOW_SWITCHER: "Панель выбора языка на сайте",
        ANONYMOUS_ACCESS: "Доступ неавторизованных пользователей",
        SHOW_POST_DATE: "Показывать даты публикации записей",
        LOGIN_SWITCHER: "Панель авторизации на сайте",
        REGISTRATION_SWITCHER: "Панель регистрации на сайте",
        COMMENTS_ENABLE: "Комментарии",
        ANONYMOUS_COMMENTS:
            "Неавторизованные пользователи могут комментировать",
        RECAPCHA_COMMENTS: "Капча к комментариям",
        CATEGORIES_ENABLE: "Категории",
        CATEGORIES_TREE_LPANEL: "Вывод категорий древовидный",
        RSS_ENABLE: "Рассылки",
        RECAPCHA_PUBLIC_KEY: "RECAPCHA открытый ключ",
        RECAPCHA_PRIVATE_KEY: "RECAPCHA закрытый ключ",

        Reset: "Сброс",

        Setting_reset_success: "Настройки успешно сброшены",
        Setting_save_success: "Настройки успешно сохранены",
        Error_save_settings: "Ошибка сохранения настроек",
        Error_load_settings: "Ошибка загрузки настроек",
        //---Settings

        To_reset_pass_lnk_sent:
            "Для сброса пароля на ваш e-mail была отправлена ссылка",
        Error_category_moving: "Ошибка перемещения категории",
        Comments_delete_success: "Комментарии успешно удалены",
        Comments_save_success: "Комментарии успешно сохранены",
        Language_delete_success: "Язык успешно удален",
        Language_added_success: "Язык успешно добавлен",
        Rss_delete_success: "Лента успешно удалена",
        Rss_added_success: "Лента успешно добавлена",
        Rss_saved_success: "Лента успешно сохранена",
        Users_delete_success: "Пользователи успешно удалены",
        Privelege_set_success: "Привелегии успешно установлены",
        Users_added_success: "Пользователи успешно добавлены",
        User_saved_success: "Пользователь успешно сохранен",

        Users_privelege_set: "Привелегии успешно установлены",
        User_saving: "Сохранение пользователя",
        Users_loading: "Загрузка пользователей",
        Users_blocking: "Блокировка пользователей",
        User_adding: "Добавление пользователя",
        User_removing: "Удаление пользователя"
    },

    en: {
        //Client
        //+++Main page
        CL_Main: "Home",
        CL_News: "News",
        CL_Enter: "Login",
        CL_All_categories: "All categories",
        CL_Search: "Search",
        Server_is_not_connected: "Server is not connected",
        //---Main page

        //+++Common
        Add: "Add",
        Remove: "Remove",
        Search: "Search",
        GotoPage: "go to",
        Content_language: "Content language",
        Cancel: "Cancel",
        Save: "Save",
        Adding: "Adding",
        Saving: "Saving",
        Find: "Find",
        Title: "Title",
        Author: "Author",
        Creation_date: "Date creation",
        Publish_date: "Publication date",
        Date: "Date",
        Published: "Published",
        Yes: "Yes",
        No: "No",
        Block: "Block",
        Registered: "Registered",
        User: "User",
        //---Common

        //+++auth/register forms
        authentication: "Enter",
        registration: "Registration",
        rememberme: "Remember me",
        login: "Login",
        password: "Password",
        password_repeat: "Password repeat",
        forgot_password: "Forgot password",
        enter: "Enter",
        reset_password: "Reset password",
        email: "E-mail",
        back: "Back",
        register: "Register",
        first_name: "First name",
        middle_name: "Middle name",
        last_name: "Last name",
        nick: "Nick",
        phone: "Phone",
        user_icon: "User icon",
        site: "Website",

        Error_login: "Login Error",
        Error_logout: "Logout Error",
        Registration_success: "Registration successful",
        Error_reset_password: "Error reset password",
        Error_Registration: "Error Registration",
        Please_login_again: "Please login again",
        Error_fields_fill: "Not all fields are filled in correctly",
        Reset_pass_link_sent:
            "To reset the password, a link has been sent to your e-mail",
        //---auth/register forms

        //+++Left panel
        AdminPanel: "Admin Panel",
        dashboard: "Dashboard",
        categories: "Categories",
        posts: "Posts",
        files: "Files",
        comments: "Comments",
        grids: "Grids",
        menus: "Menu",
        plugins: "Plugins",
        rss: "RSS",
        themes: "Themes",
        widgets: "Widgets",
        lang: "Languages",
        tools: "Tools",
        users: "Users",
        rollup: "Rollup",
        settings: "Settings",
        //---Left panel

        //+++Dashboard
        Loading: "Loading",
        Publish_posts_by_months: "Posts by months",
        Publish_categories_by_months: "Categories by months",
        Publish_comments_by_months: "Comments by months",
        Registration_users_by_months: "Users registered by months",
        January: "January",
        February: "February",
        March: "March",
        April: "April",
        May: "May",
        June: "June",
        July: "July",
        August: "August",
        September: "September",
        October: "October",
        November: "November",
        December: "December",

        Error_load_graphs: "Error loading graphs",
        //---Dashboard

        //+++Categories
        Categories_loading: "Categories loading",
        Categories_removing: "Categories removing",
        Categories_moving: "Categories moving",
        Category_name: "Category name",
        Category_find: "Find category",
        Move_down: "Move down",
        Move_up: "Move up",
        Edit_category: "Edit category",
        Remove_category: "Remove category",
        Enter_category: "Enter category",
        Category_saving: "Category saving",
        Copy_to_All_Languages: "Copy to All Languages",
        New_category_name: "New category name",
        Autonumerate: "Auto-numbering",
        Out_order: "Output order",
        by_date: "by date",
        by_date_back: "by date reverse",
        by_numbers: "by numbers",
        by_numbers_back: "by numbers reverse",
        Keywords: "Keywords",
        Filed_name: "Filed name",
        User_fields: "User fields",
        Category_adding: "Category adding",
        Add_category: "Add category",
        Categories_selection: "Categories selection",
        Selected: "Selected",

        Error_load_categories: "Error obtaining categories",
        Category_adding_success: "Category added successfully",
        Error_category_adding: "Error adding category",
        Category_save_success: "Category saved successfully",
        Error_category_saving: "Error saving category",
        Category_remove_success: "Categories removed successfully",
        Error_category_removing: "Error removing categories",
        Categories_not_selected: "Categories does not selected",
        Error_category_moving: "Error moving categories",
        //---Categories

        //+++Posts
        Posts_loading: "Posts loading",
        Post_data_loading: "Post data loading",
        Posts_removing: "Posts removing",
        By_post_header: "By post title",
        By_post_text: "By post text",
        Find_post: "Find post",
        Edit_post: "Edit post",
        Remove_post: "Remove post",
        Category_not_selected: "Category not selected",
        Select_category_of_posts: "Select category of posts",
        Preview: "Preview",
        Close_preview: "Close preview",
        Add_post: "Add post",
        Back_to_posts_list: "Back to posts list",
        Publish: "Publish",
        Post_title: "Post title",
        Add_Image: "Add Image",
        Order_By_Hand: "Order by hand",
        Post_Number_Forward_Direction: "Post number forward direction",
        Post_Number_Backward_Direction: "Post number backward direction",
        Published: "Published",
        NotPublished: "Not Published",
        Status: "Status",
        Category: "Category",

        Error_load_paginator_data: "Error loading post data",
        Error_load_posts: "Error loading posts",
        Posts_remove_success: "Entries removing successfully",
        Error_remove_posts: "Error removing posts",
        Posts_not_selected_to_delete: "Posts does not selected to remove",
        Error_load_onepost: "Error loading post",
        Error_save_onepost: "Error saving post",
        Error_find_posts: "Error finding posts",
        Post_publish_success: "Post published successfully",
        Post_save_success: "Post saved successfully",
        Error_add_post: "Error adding post",
        //---Posts

        //+++Files
        Files_Not_Selected: "Files does not selected",
        Select_operations: "Selective operations",
        Select_All_Visible: "Select all visible",
        Unselect_All_Visible: "Unselect all visible",
        Select_All: "Select all",
        Unselect_All: "Unselect all",
        Find_images: "Find images",
        Image_title: "Image title",
        Edit_title: "Edit title",
        Image_loading: "Image loading",
        Image_removing: "Image removing",
        Add_file: "Add file",
        Select_file: "Select file",
        Image_width: "Image width",
        Image_height: "Image height",
        Back_to_media_store: "Back to media store",
        File_does_not_selected: "File does not selected",
        Local_file: "Local file",
        FromInternet: "From internet",
        FromMediaStore: "From media store",
        Link: "Link",

        Error_load_files: "Error loading files",
        File_load_success: "File upload successfully",
        Error_load_file: "Error uploading file",
        Files_remove_success: "Files removed successfully",
        Error_remove_files: "Error removing files",
        File_save_success: "File saved successfully",
        Error_save_file: "Error saving file",
        //---Files

        //+++Comments
        Comments_loading: "Comments loading",
        Comments_user_blocking: "Users blocking",
        Comments_removing: "Comments removing",
        Comments_saving: "Comments saving",
        Comments_searching: "Search comments",
        Comments_user_loading: "Comments loading",
        Comments_categories_loading: "Categories loading",
        Filter_By: "Filter by",
        All_comments: "All comments",
        By_users: "By users",
        By_posts: "By posts",
        By_Categories: "By categories",
        No_comments_select_to_block: "No comments selected to block",
        No_comments_select_to_remove: "No comments selected to remove",
        Part_text_comment: "Fragment of comment text",
        List_view: "List",
        Tree_view: "Tree",
        blocked: "blocked",
        active: "active",
        Edit_comment: "Edit comment",
        Block_user: "Block user",
        Remove_comment: "Remove comment",
        Find_comment: "Find comment",
        Users_not_selected: "Users does not selected",
        Comments_delete_of_seleceted_users: "Remove comments of selected users",
        Comments_count: "Comments",
        All_comments_of_current_user: "All comments of the current user",
        Comments_of_user: "Comments of user",
        Back_to_comments: "Back to comments list",
        Posts_not_selected: "Posts does not selected",
        Comments_remove_selected_users: "Remove comments of selected users",
        All_comments_of_current_post: "All comments of the current post",
        Post_comments: "Post comments",
        Back_to_posts: "Back to posts list",
        Category_not_selected: "Categories does not selected",
        Remove_comments: "Remove comments",
        Remove_comments_of_category: "Remove comments of the category",
        All_comments_of_current_category:
            "All comments of the current category",
        Comment: "Comment",
        Back_to_categories: "Back to categories",

        Error_block_users: "Error blocking users",
        Error_remove_comments: "Error removing comments",
        Error_save_comments: "Error saving comment",
        Error_find_comments: "Error searching comments",
        Comments_not_selected: "Comments does not selected",
        Error_load_comments: "Error loading comments",
        Users_block_success: "Users Block Success",
        //---Comments

        //+++RSS
        No_rss_selected: "Rss does not selected",
        Rss_fragment_header: "Fragment RSS header",
        Rss_title: "Title RSS",
        Rss_add: "Add RSS",
        Rss_remove: "Remove RSS",
        Rss_find: "Search RSS",
        Description: "Description",
        Rss_one_remove: "RSS remove",
        Rss_one_edit: "Edit RSS",
        Rss_adding: "RSS adding",
        Back_to_rss_list: "Back to RSS list",
        Selected_categories: "Selected categories",
        Rss_edit: "Edit RSS",
        Rss_loading: "RSS Loading",

        Error_load_rss: "Error loading news feeds",
        Error_remove_rss: "Error removing news feeds",
        Error_add_rss: "Error adding news feed",
        Error_save_rss: "Error saving news feed",
        Rss_updating: "RSS Updating",
        Rss_removing: "RSS removing",
        //---RSS

        //+++Lang
        russian: "Russian",
        english: "English",
        german: "German",
        chinese: "Chinese",
        Russian: "Russian",
        English: "English",
        German: "German",
        Chinese: "Chinese",

        ru: "Russian",
        en: "English",
        de: "German",
        zh: "Chinese",
        Error_load_langs: "Error loading languages",
        Error_remove_lang: "Error removing languages",
        Error_add_lang: "Error adding languages",

        Min_one_lang_must_be_set: "Minimum one language must be set",
        Langs_loading: "Languages loading",
        Langs_adding: "Languages adding",
        Langs_removing: "Languages removing",
        UI_Language: "Interface Language",
        Select_User_Interface_Language: "Select user interface language",
        Show_content_language_switcher_on_frontend:
            "Show content language switcher on frontend",
        Content_Languages: "Content Languages",
        All_Languages: "All Languages",
        Find_by: "Find by",
        By_email: "By email",
        By_first_name: "By first name",
        By_middle_name: "By middle name",
        By_last_name: "By last name",
        By_nick: "By nick",
        By_phone: "By phone",
        By_site: "By site",
        //---Lang

        //+++Users
        Privilege: "Privilege",
        User_privelege: "User privelege",
        Users_privelege: "Users privelege",
        User_edit: "Edit user",
        User_remove: "Remove user",
        Back_to_user_list: "Back to user list",
        Files_management: "Files management",
        Admin_access: "Admin access",
        Category_Write: "Category Write",
        Category_Read: "Category Read",
        Users_Write: "Users Write",
        Users_Read: "Users Read",
        Posts_Write: "Posts Write",
        Posts_Read: "Posts Read",
        Priv_Blocked: "Blocked",
        User_add: "User add",
        Back_to_users: "Back to user list",
        Users_loading: "Users loading",

        Error_load_users: "Error loading users",
        Error_block_users: "Error blocking users",
        Error_remove_users: "Error removing users",
        Error_save_privs: "Error saving privileges",
        Error_add_user: "Error adding user",
        Error_save_user: "Error saving user",
        //---Users

        //+++Settings
        SITE_TITLE: "Web site title",
        KEYWORDS: "Keywords",
        DESCRIPTION: "Web site description",
        LANGS_SHOW_SWITCHER: "Select language panel on website",
        ANONYMOUS_ACCESS: "Access for not registered users",
        SHOW_POST_DATE: "Show post date",
        LOGIN_SWITCHER: "Authorization panel on website",
        REGISTRATION_SWITCHER: "Registration panel on website",
        COMMENTS_ENABLE: "Comments",
        ANONYMOUS_COMMENTS: "Anonymous users comments",
        RECAPCHA_COMMENTS: "COMMENTS CAPCHA",
        CATEGORIES_ENABLE: "Categories",
        CATEGORIES_TREE_LPANEL: "Categories as Tree",
        RSS_ENABLE: "RSS",
        RECAPCHA_PUBLIC_KEY: "RECAPCHA PUBLIC KEY",
        RECAPCHA_PRIVATE_KEY: "RECAPCHA PRIVATE KEY",
        Reset: "Reset",

        Setting_reset_success: "Settings reset successfully",
        Setting_save_success: "Settings saved successfully",
        Error_save_settings: "Error saving settings",
        Error_load_settings: "Error loading settings",
        //---Settings

        To_reset_pass_lnk_sent:
            "To reset password the link were sent to your e-mail",
        Error_category_moving: "Error category moving",
        Comments_delete_success: "Comments successfully deleted",
        Comments_save_success: "Comments successfully saved",
        Language_delete_success: "The language was successfully deleted",
        Language_added_success: "The language was successfully added",
        Rss_delete_success: "The RSS was successfully deleted",
        Rss_added_success: "The RSS was successfully added",
        Rss_saved_success: "The RSS was successfully saved",
        Users_delete_success: "Users successfully deleted",
        Privelege_set_success: "Privileges successfully set",
        Users_added_success: "Users successfully added",
        User_saved_success: "User successfully saved",

        Users_privelege_set: "Privileges successfully set",
        User_saving: "User saving",
        Users_loading: "Users loading",
        Users_blocking: "Users blocking",
        User_adding: "User adding",
        User_removing: "User removing"
    },

    de: {
        //Client
        //+++Main page
        CL_Main: "Zuhause",
        CL_News: "Nachrichten",
        CL_Enter: "Login",
        CL_All_categories: "Alle Kategorien",
        CL_Search: "Finden",
        Server_is_not_connected: "Server ist nicht verbunden",
        //---Main page

        //+++Common
        Add: "Hinzufügen",
        Remove: "Löschen",
        Search: "Finden",
        GotoPage: "Gehe zu",
        Content_language: "Inhaltssprache",
        Cancel: "Abbrechen",
        Save: "Speichern",
        Adding: "Hinzufügen",
        Saving: "Speichern",
        Find: "Suche",
        Title: "Titel",
        Author: "Autor",
        Creation_date: "Erstellungsdatum",
        Publish_date: "Veröffentlichungsdatum",
        Date: "Datum",
        Published: "Veröffentlicht",
        Yes: "Ja",
        No: "Nein",
        Block: "Blockieren",
        Registered: "Registriert",
        User: "Benutzer",
        //---Common

        //+++auth/register forms
        authentication: "Login",
        registration: "Registrierung",
        rememberme: "Erinnere dich an mich",
        login: "Login",
        password: "Passwort",
        password_repeat: "Passwort wiederholen",
        forgot_password: "Passwort vergessen",
        enter: "Login",
        reset_password: "Passwort zurücksetzen",
        email: "E-mail",
        back: "Zurück",
        register: "Registrieren",
        first_name: "Name",
        middle_name: "Nachname",
        last_name: "Patronymisch",
        nick: "Alias",
        phone: "Telefon",
        user_icon: "Benutzersymbol",
        site: "Website",

        Error_login: "Autorisierungsfehler",
        Error_logout: "Logout Fehler",
        Registration_success: "Registrierung erfolgreich",
        Error_reset_password: "Fehler beim Zurücksetzen des Passworts",
        Error_Registration: "Fehlerregistrierung",
        Please_login_again: "Bitte melden Sie sich erneut an",
        Error_fields_fill: "Nicht alle Felder sind korrekt ausgefüllt",
        Reset_pass_link_sent:
            "Um das Passwort zurückzusetzen, wurde ein Link zu Ihrer E-Mail gesendet",
        //---auth/register forms

        //+++Left panel
        AdminPanel: "Systemsteuerung",
        dashboard: "Zuhause",
        categories: "Kategorien",
        posts: "Einträge",
        files: "Dateien",
        comments: "Kommentare",
        grids: "Rastermasche",
        menus: "Menü",
        plugins: "Plugins",
        rss: "Newsletter",
        themes: "Themen",
        widgets: "Widgets",
        lang: "Sprachen",
        tools: "Werkzeuge",
        users: "Benutzer",
        rollup: "Collapse",
        settings: "die Einstellungen",
        //---Left panel

        //+++Dashboard
        Loading: "Laden",
        Publish_posts_by_months: "Veröffentlichungen nach Monat",
        Publish_categories_by_months:
            "Veröffentlichungen von Kategorien nach Monat",
        Publish_comments_by_months:
            "Veröffentlichungen von Kommentaren nach Monat",
        Registration_users_by_months: "Benutzerregistrierung nach Monat",
        January: "Januar",
        February: "Februar",
        March: "März",
        April: "April",
        May: "Mai",
        June: "Juni",
        July: "Juli",
        August: "August",
        September: "September",
        October: "Oktober",
        November: "November",
        December: "Dezember",

        Error_load_graphs: "Fehler beim Laden der Diagramme",
        //---Dashboard

        //+++Categories
        Categories_loading: "Kategorien werden geladen",
        Categories_removing: "Kategorien werden gelöscht",
        Categories_moving: "Kategorien werden übertragen",
        Category_name: "Kategoriename",
        Category_find: "Suche nach Kategorien",
        Move_down: "Nach unten",
        Move_up: "Nach oben",
        Edit_category: "Kategorie bearbeiten",
        Remove_category: "Kategorie löschen",
        Enter_category: "Geben Sie die Kategorie ein",
        Category_saving: "Kategorie wird gespeichert",
        Copy_to_All_Languages: "In alle Sprachen kopieren",
        New_category_name: "Name der neuen Kategorie",
        Autonumerate: "Auto-Nummerierung",
        Out_order: "Ausgabeauftrag",
        by_date: "nach Daten",
        by_date_back: "Nach Datum",
        by_numbers: "nach Zahlen",
        by_numbers_back: "nach Zahlen zurück",
        Keywords: "Keywords",
        Filed_name: "Feldname",
        User_fields: "Benutzerdefinierte Felder",
        Category_adding: "Kategorie wird hinzugefügt",
        Add_category: "Kategorie hinzufügen",
        Categories_selection: "Kategorienauswahl",
        Selected: "Ausgewählt",

        Error_load_categories: "Fehler beim Abrufen von Kategorien",
        Category_adding_success: "Kategorie erfolgreich hinzugefügt",
        Error_category_adding: "Fehler beim Hinzufügen der Kategorie",
        Category_save_success: "Kategorie erfolgreich gespeichert",
        Error_category_saving: "Fehler beim Speichern der Kategorie",
        Category_remove_success: "Kategorien erfolgreich gelöscht",
        Error_category_removing: "Fehler beim Entfernen von Kategorien",
        Categories_not_selected: "Kategorien sind nicht ausgewählt",
        Error_category_moving: "Fehler beim Verschieben von Kategorien",
        //---Categories

        //+++Posts
        Posts_loading: "Einträge werden geladen",
        Post_data_loading: "Datensatzdaten laden",
        Posts_removing: "Einträge werden gelöscht",
        By_post_header: "Nach Titel",
        By_post_text: "Im Text des Eintrags",
        Find_post: "Eintrag finden",
        Edit_post: "Datensatz bearbeiten",
        Remove_post: "Eintrag löschen",
        Category_not_selected: "Kategorie nicht ausgewählt",
        Select_category_of_posts: "Auswahl einer Kategorie von Datensätzen",
        Preview: "Vorschau",
        Close_preview: "Vorschau schließen",
        Add_post: "Einen Eintrag hinzufügen",
        Back_to_posts_list: "Zurück zur Liste der Einträge",
        Publish: "Veröffentlichen",
        Post_title: "Titel aufzeichnen",
        Add_Image: "Bild hinzufügen",
        Order_By_Hand: "Manuelle Nummerierung",
        Post_Number_Forward_Direction:
            "Die Datensatznummer ist die direkte Bestellung",
        Post_Number_Backward_Direction:
            "Nummer der umgekehrten Auftragseingabe",
        Published: "Veröffentlicht",
        NotPublished: "Nicht veröffentlicht",
        Status: "Status",
        Category: "Kategorie",

        Error_load_paginator_data: "Fehler beim Abrufen von Datensatzdaten",
        Error_load_posts: "Fehler beim Abrufen der Datensätze",
        Posts_remove_success: "Einträge erfolgreich gelöscht",
        Error_remove_posts: "Fehler beim Entfernen von Datensätzen",
        Posts_not_selected_to_delete:
            "Es wurde kein Eintrag zum Löschen ausgewählt",
        Error_load_onepost: "Fehler beim Laden des Datensatzes",
        Error_save_onepost: "Fehler beim Speichern des Datensatzes",
        Error_find_posts: "Fehler beim Suchen von Datensätzen",
        Post_publish_success: "Record erfolgreich veröffentlicht",
        Post_save_success: "Aufzeichnung erfolgreich gespeichert",
        Error_add_post: "Fehler beim Hinzufügen des Datensatzes",
        //---Posts

        //+++Files
        Files_Not_Selected: "Es wurden keine Dateien zum Löschen ausgewählt",
        Select_operations: "Operationen auswählen",
        Select_All_Visible: "Alles sichtbar auswählen",
        Unselect_All_Visible: "Alle sichtbaren abwählen",
        Select_All: "Alles auswählen",
        Unselect_All: "Alle abwählen",
        Find_images: "Bilder finden",
        Image_title: "Bildkopf",
        Edit_title: "Titel bearbeiten",
        Image_loading: "Bild herunterladen",
        Image_removing: "Bilder löschen",
        Add_file: "Eine Datei hinzufügen",
        Select_file: "Datei auswählen",
        Image_width: "Bildbreite",
        Image_height: "Bildhöhe",
        Back_to_media_store: "Zurück zur Dateiliste",
        File_does_not_selected: "Datei nicht ausgewählt",
        Local_file: "Datei von Festplatte",
        FromInternet: "Aus dem Internet",
        FromMediaStore: "Aus dem Repository",
        Link: "Link",

        Error_load_files: "Fehler beim Abrufen der Liste der Dateien",
        File_load_success: "Datei erfolgreich heruntergeladen",
        Error_load_file: "Fehler beim Herunterladen der Datei",
        Files_remove_success: "Dateien erfolgreich gelöscht",
        Error_remove_files: "Fehler beim Löschen von Dateien",
        File_save_success: "Datei erfolgreich gespeichert",
        Error_save_file: "Fehler beim Speichern der Datei",
        //---Files

        //+++Comments
        Comments_loading: "Kommentare werden geladen",
        Comments_user_blocking: "Benutzer blockieren",
        Comments_removing: "Kommentare löschen",
        Comments_saving: "Kommentare speichern",
        Comments_searching: "Nach Kommentaren suchen",
        Comments_user_loading: "Benutzerkommentare herunterladen",
        Comments_categories_loading: "Kategorien laden",
        Filter_By: "Filtern nach",
        All_comments: "Alle Kommentare",
        By_users: "Nach Benutzern",
        By_posts: "Nach Datensätzen",
        By_Categories: "Nach Kategorie",
        No_comments_select_to_block:
            "Es wurden keine Kommentare zum Blockieren ausgewählt",
        No_comments_select_to_remove:
            "Es wurden keine Kommentare zum Löschen ausgewählt",
        Part_text_comment: "Fragment des Kommentartextes",
        List_view: "Liste",
        Tree_view: "Baum",
        blocked: "blockiert",
        active: "aktiv",
        Edit_comment: "Kommentar bearbeiten",
        Block_user: "Benutzer blockieren",
        Remove_comment: "Kommentar löschen",
        Find_comment: "Finde einen Kommentar",
        Users_not_selected: "Kein Benutzer ausgewählt",
        Comments_delete_of_seleceted_users:
            "Ausgewählte Benutzerkommentare löschen",
        Comments_count: "Kommentare",
        All_comments_of_current_user: "Alle Kommentare dieses Benutzers",
        Comments_of_user: "Benutzerkommentare",
        Back_to_comments: "Zurück zu den Kommentaren",
        Posts_not_selected: "Kein Eintrag ausgewählt",
        Comments_remove_selected_users:
            "Ausgewählte Benutzerkommentare löschen",
        All_comments_of_current_post: "Alle Kommentare zu diesem Eintrag",
        Post_comments: "Kommentar zum Eintrag",
        Back_to_posts: "Zurück zu den Beiträgen",
        Category_not_selected: "Keine Kategorie ausgewählt",
        Remove_comments: "Kommentare löschen",
        Remove_comments_of_category: "Löschen von Kategorienkommentaren",
        All_comments_of_current_category: "Alle Kommentare in dieser Kategorie",
        Comment: "Kommentar",
        Back_to_categories: "Zurück zu Kategorien",

        Error_block_users: "Benutzersperrfehler",
        Error_remove_comments: "Fehler beim Löschen von Kommentaren",
        Error_save_comments: "Fehler beim Speichern des Kommentars",
        Error_find_comments: "Fehler beim Suchen nach Kommentaren",
        Comments_not_selected: "Keine Kommentare ausgewählt",
        Error_load_comments: "Fehler beim Laden der Kommentare",
        Users_block_success: "Benutzer wurden erfolgreich blockiert",
        //---Comments

        //+++RSS
        No_rss_selected: "Keine Newsletter ausgewählt",
        Rss_fragment_header: "Ribbon-Header-Fragment",
        Rss_title: "Ribbon Header",
        Rss_add: "Newsletter hinzufügen",
        Rss_remove: "Newsletter entfernen",
        Rss_find: "Finde einen Newsletter",
        Description: "Beschreibung",
        Rss_one_remove: "Newsletter löschen",
        Rss_one_edit: "Verteilung bearbeiten",
        Rss_adding: "Eine Mailingliste hinzufügen",
        Back_to_rss_list: "Zurück zur Mailingliste",
        Selected_categories: "Ausgewählte Kategorien",
        Rss_edit: "Verteilung bearbeiten",
        Rss_loading: "Bänder werden geladen",

        Error_load_rss: "Fehler beim Abrufen von Mailings",
        Error_remove_rss: "Fehler beim Löschen von Newsfeeds",
        Error_add_rss: "Fehler beim Hinzufügen des News-Feeds",
        Error_save_rss: "Fehler beim Speichern des Newsfeeds",
        Rss_updating: "RSS Aktualisierung",
        Rss_removing: "RSS entfernen",
        //---RSS

        //+++Lang
        russian: "russisch",
        english: "englisch",
        german: "deutsch",
        chinese: "chinesisch",
        Russian: "Russisch",
        English: "Englisch",
        German: "Deutsch",
        Chinese: "Chinesisch",

        ru: "Russisch",
        en: "Englisch",
        de: "Deutsch",
        zh: "Chinesisch",
        Error_load_langs: "Fehler beim Laden von Sprachen",
        Error_remove_lang: "Fehler beim Entfernen von Sprachen",
        Error_add_lang: "Fehler beim Hinzufügen von Sprachen",

        Min_one_lang_must_be_set: "Mindestens eine Sprache ist erforderlich",
        Langs_loading: "Sprachen werden geladen",
        Langs_adding: "Sprachen hinzufügen",
        Langs_removing: "Sprachen löschen",
        UI_Language: "Interfaced Language",
        Select_User_Interface_Language: "Select interface language",
        Show_content_language_switcher_on_frontend:
            "Zeige die Sprachumschaltung auf der Seite",
        Content_Languages: "Inhaltssprachen",
        All_Languages: "Alle Sprachen",
        Find_by: "Finde nach",
        By_email: "Per E-Mail",
        By_first_name: "Nach Name",
        By_middle_name: "Von Vatersnamen",
        By_last_name: "Nach Nachname",
        By_nick: "Nach dem Pseudonym",
        By_phone: "Am Telefon",
        By_site: "Nach Ort",
        //---Lang

        //+++Users
        Privilege: "Privileg",
        User_privelege: "Benutzerrechte",
        Users_privelege: "Benutzerrechte",
        User_edit: "Benutzer bearbeiten",
        User_remove: "Benutzer löschen",
        Back_to_user_list: "Zurück zur Benutzerliste",
        Files_management: "Arbeiten mit Dateien",
        Admin_access: "Administratorzugriff",
        Category_Write: "Record categories",
        Category_Read: "Lesekategorien",
        Users_Write: "Benutzer aufzeichnen",
        Users_Read: "Benutzer lesen",
        Posts_Write: "Beiträge veröffentlichen",
        Posts_Read: "Beiträge lesen",
        Priv_Blocked: "Blockieren",
        User_add: "Benutzer hinzufügen",
        Back_to_users: "Zurück zur Benutzerliste",
        Users_loading: "Benutzer werden geladen",

        Error_load_users: "Fehler beim Herunterladen der Benutzer",
        Error_block_users: "Benutzersperrfehler",
        Error_remove_users: "Fehler beim Entfernen der Benutzer",
        Error_save_privs: "Fehler beim Speichern von Berechtigungen",
        Error_add_user: "Fehler beim Hinzufügen des Benutzers",
        Error_save_user: "Fehler beim Speichern des Benutzers",
        //---Users

        //+++Settings
        SITE_TITLE: "Websitename",
        KEYWORDS: "Schlüsselwörter",
        DESCRIPTION: "Standortbeschreibung",
        LANGS_SHOW_SWITCHER: "Sprachauswahl auf der Webseite auswählen",
        ANONYMOUS_ACCESS: "Zugriff durch nicht autorisierte Benutzer",
        SHOW_POST_DATE: "Veröffentlichungsdatum der Publikation anzeigen",
        COMMENTS_ENABLE: "Kommentare",
        ANONYMOUS_COMMENTS:
            "Nicht autorisierte Benutzer können Kommentare abgeben",
        RECAPCHA_COMMENTS: "Captcha zu Kommentaren",
        CATEGORIES_ENABLE: "Kategorien",
        CATEGORIES_TREE_LPANEL: "Kategorie Ausgabebaum",
        RSS_ENABLE: "Newsletter",
        RECAPCHA_PUBLIC_KEY: "RECAPCHA öffentlicher Schlüssel",
        RECAPCHA_PRIVATE_KEY: "RECAPCHA privater Schlüssel",

        LOGIN_SWITCHER: "Autorisierungsgruppe auf der Website",
        REGISTRATION_SWITCHER: "Registrierungspanel auf der Website",
        Reset: "Zurücksetzen",

        Setting_reset_success: "Einstellungen erfolgreich zurückgesetzt",
        Setting_save_success: "Einstellungen erfolgreich gespeichert",
        Error_save_settings: "Fehler beim Speichern der Einstellungen",
        Error_load_settings: "Fehler beim Laden der Einstellungen",
        //---Settings

        To_reset_pass_lnk_sent:
            "Um das Passwort zurückzusetzen, wurde ein Link zu Ihrer E-Mail gesendet",
        Error_category_moving: "Fehler beim Verschieben der Kategorie",
        Comments_delete_success: "Kommentare erfolgreich gelöscht",
        Comments_save_success: "Kommentare erfolgreich gespeichert",
        Language_delete_success: "Die Sprache wurde erfolgreich gelöscht",
        Language_added_success: "Sprache erfolgreich hinzugefügt",
        Rss_delete_success: "Das Band wurde erfolgreich gelöscht",
        Rss_added_success: "Der Feed wurde erfolgreich hinzugefügt",
        Rss_saved_success: "Das Band wurde erfolgreich gespeichert",
        Users_delete_success: "Benutzer erfolgreich gelöscht",
        Privelege_set_success: "Privilegien erfolgreich installiert",
        Users_added_success: "Benutzer erfolgreich hinzugefügt",
        User_saved_success: "Benutzer erfolgreich gespeichert",

        Users_privelege_set: "Berechtigungen erfolgreich installiert",
        User_saving: "Benutzer speichern",
        Users_loading: "Benutzer hochladen",
        Users_blocking: "Benutzer blockieren",
        User_adding: "Einen Benutzer hinzufügen",
        User_removing: "Einen Benutzer löschen"
    },

    zh: {
        //Client
        //+++Main page
        CL_Main: "主要的",
        CL_News: "新闻",
        CL_Enter: "进入",
        CL_All_categories: "所有类别",
        CL_Search: "查找",
        Server_is_not_connected: "服务器未连接",
        //---Main page

        //+++Common
        Add: "添加",
        Remove: "删除",
        Search: "查找",
        GotoPage: "去到 翻到",
        Content_language: "内容语言",
        Cancel: "取消",
        Save: "保存",
        Adding: "添加",
        Saving: "保存",
        Find: "搜索",
        Title: "标题",
        Author: "作者",
        Creation_date: "创建日期",
        Publish_date: "发布日期",
        Date: "日期",
        Published: "已发布",
        Yes: "是",
        No: "否",
        Block: "锁定",
        Registered: "注册",
        User: "用户",
        //---Common

        //+++auth/register forms
        authentication: "入口",
        registration: "注册",
        rememberme: "记住我",
        login: "登录",
        password: "密码",
        password_repeat: "重复密码",
        forgot_password: "忘记密码",
        enter: "入口",
        reset_password: "重置密码",
        email: "电子邮件",
        back: "返回",
        register: "注册",
        first_name: "名",
        middle_name: "姓氏",
        last_name: "父称",
        nick: "别名",
        phone: "电话",
        user_icon: "用户图标",
        site: "网站",

        Error_login: "授权错误",
        Error_logout: "注销错误",
        Registration_success: "注册成功",
        Error_reset_password: "错误重置密码",
        Error_Registration: "错误注册",
        Please_login_again: "请再次登录",
        Error_fields_fill: "并非所有字段都填写正确",
        Reset_pass_link_sent:
            "Для сброса пароля на ваш e-mail отправлена ссылка",
        //---auth/register forms

        //+++Left panel
        AdminPanel: "控制面板",
        dashboard: "主要的",
        categories: "类别",
        posts: "记录",
        files: "文件",
        comments: "评论",
        grids: "标记网格",
        menus: "菜单",
        plugins: "插件",
        rss: "邮件列表",
        themes: "主题",
        widgets: "小工具",
        lang: "语言",
        tools: "工具",
        users: "用户",
        rollup: "折叠",
        settings: "设置",
        //---Left panel

        //+++Dashboard
        Loading: "加载",
        Publish_posts_by_months: "按月记录的出版物",
        Publish_categories_by_months: "按月分类的出版物",
        Publish_comments_by_months: "按月发表评论",
        Registration_users_by_months: "按月登记用户",
        January: "一月",
        February: "二月",
        March: "三月",
        April: "四月",
        May: "五月",
        June: "六月",
        July: "七月",
        August: "八月",
        September: "九月",
        October: "十月",
        November: "十一月",
        December: "十二月",

        Error_load_graphs: "加载图表时出错",
        //---Dashboard

        //+++Categories
        Categories_loading: "分类被加载",
        Categories_removing: "类别被删除",
        Categories_moving: "分类已转移",
        Category_name: "分类名称",
        Category_find: "搜索类别",
        Move_down: "下移",
        Move_up: "上移",
        Edit_category: "编辑类别",
        Remove_category: "删除类别",
        Enter_category: "输入类别",
        Category_saving: "类别已保存",
        Copy_to_All_Languages: "复制到所有语言",
        New_category_name: "新类别的名称",
        Autonumerate: "自动编号",
        Out_order: "输出顺序",
        by_date: "按日期",
        by_date_back: "按日期返回",
        by_numbers: "按数字",
        by_numbers_back: "通过数字返回",
        Keywords: "关键字",
        Filed_name: "字段名称",
        User_fields: "自定义字段",
        Category_adding: "添加的类别",
        Add_category: "添加类别",
        Categories_selection: "分类选择",
        Selected: "选",

        Error_load_categories: "获取类别错误",
        Category_adding_success: "成功添加类别",
        Error_category_adding: "错误添加类别",
        Category_save_success: "成功保存类别",
        Error_category_saving: "保存类别错误",
        Category_remove_success: "成功删除类别",
        Error_category_removing: "删除类别错误",
        Categories_not_selected: "类别未选中",
        Error_category_moving: "错误的移动类别",
        //---Categories

        //+++Posts
        Posts_loading: "条目被加载",
        Post_data_loading: "加载记录数据",
        Posts_removing: "条目被删除",
        By_post_header: "按标题",
        By_post_text: "通过条目的文本",
        Find_post: "查找条目",
        Edit_post: "编辑记录",
        Remove_post: "删除条目",
        Category_not_selected: "未选择类别",
        Select_category_of_posts: "选择记录类别",
        Preview: "预览",
        Close_preview: "关闭预览",
        Add_post: "添加条目",
        Back_to_posts_list: "返回条目列表",
        Publish: "发布",
        Post_title: "记录的标题",
        Add_Image: "添加图片",
        Order_By_Hand: "手动编号",
        Post_Number_Forward_Direction: "记录号码是直接的顺序",
        Post_Number_Backward_Direction: "记录的编号是相反的顺序",
        Published: "已发布",
        NotPublished: "未发布",
        Status: "状态",
        Category: "类别",

        Error_load_paginator_data: "获取记录数据出错",
        Error_load_posts: "获取记录错误",
        Posts_remove_success: "条目已成功删除",
        Error_remove_posts: "删除记录时出错",
        Posts_not_selected_to_delete: "没有条目被选中删除",
        Error_load_onepost: "加载记录时出错",
        Error_save_onepost: "保存记录错误",
        Error_find_posts: "查找记录时出错",
        Post_publish_success: "成功发布记录",
        Post_save_success: "成功保存记录",
        Error_add_post: "错误添加记录",
        //---Posts

        //+++Files
        Files_Not_Selected: "没有文件被选择删除",
        Select_operations: "选择操作",
        Select_All_Visible: "全选可见",
        Unselect_All_Visible: "取消选择所有可见",
        Select_All: "全选",
        Unselect_All: "取消全选",
        Find_images: "查找图片",
        Image_title: "图片标题",
        Edit_title: "编辑标题",
        Image_loading: "加载图片",
        Image_removing: "删除图片",
        Add_file: "添加文件",
        Select_file: "选择文件",
        Image_width: "图片宽度",
        Image_height: "图片高度",
        Back_to_media_store: "返回文件列表",
        File_does_not_selected: "未选择文件",
        Local_file: "来自磁盘的文件",
        FromInternet: "从互联网上",
        FromMediaStore: "从存储",
        Link: "链接",

        Error_load_files: "错误获取文件列表",
        File_load_success: "文件成功下载",
        Error_load_file: "下载文件出错",
        Files_remove_success: "成功删除的文件",
        Error_remove_files: "错误删除文件",
        File_save_success: "文件成功保存",
        Error_save_file: "保存文件出错",
        //---Files

        //+++Comments
        Comments_loading: "加载评论",
        Comments_user_blocking: "阻止用户",
        Comments_removing: "删除评论",
        Comments_saving: "保存评论",
        Comments_searching: "查找评论",
        Comments_user_loading: "下载用户评论",
        Comments_categories_loading: "加载类别",
        Filter_By: "以什么途径过滤",
        All_comments: "所有评论",
        By_users: "按用户",
        By_posts: "按记录",
        By_Categories: "按类别",
        No_comments_select_to_block: "未选择阻止评论",
        No_comments_select_to_remove: "没有评论被选中删除",
        Part_text_comment: "评论文字的片段",
        List_view: "清单",
        Tree_view: "树",
        blocked: "封锁",
        active: "活跃",
        Edit_comment: "编辑评论",
        Block_user: "阻止用户",
        Remove_comment: "删除评论",
        Find_comment: "查找评论",
        Users_not_selected: "没有用户选择",
        Comments_delete_of_seleceted_users: "删除选定的用户评论",
        Comments_count: "评论",
        All_comments_of_current_user: "此用户的所有评论",
        Comments_of_user: "用户评论",
        Back_to_comments: "返回到评论",
        Posts_not_selected: "没有记录被选中",
        Comments_remove_selected_users: "删除所选用户的评论",
        All_comments_of_current_post: "此条目的所有评论",
        Post_comments: "对条目的评论",
        Back_to_posts: "回到帖子",
        Category_not_selected: "没有选择分类",
        Remove_comments: "删除评论",
        Remove_comments_of_category: "删除类别评论",
        All_comments_of_current_category: "此分类中的所有评论",
        Comment: "评论",
        Back_to_categories: "返回到类别",

        Error_block_users: "用户锁定错误",
        Error_remove_comments: "删除评论时出错",
        Error_save_comments: "保存评论错误",
        Error_find_comments: "搜索评论时出错",
        Comments_not_selected: "未选择任何评论",
        Error_load_comments: "加载评论时出错",
        Users_block_success: "用户成功阻止",
        //---Comments

        //+++RSS
        No_rss_selected: "邮件列表没有选择",
        Rss_fragment_header: "功能区标题片段",
        Rss_title: "标题片段",
        Rss_add: "添加邮件列表",
        Rss_remove: "删除邮件列表",
        Rss_find: "查找邮件列表",
        Description: "描述",
        Rss_one_remove: "删除邮件列表",
        Rss_one_edit: "编辑邮件列表",
        Rss_adding: "添加邮件列表",
        Back_to_rss_list: "返回邮件列表",
        Selected_categories: "所选类别",
        Rss_edit: "编辑邮件列表",
        Rss_loading: "加载色带",

        Error_load_rss: "收到邮件错误",
        Error_remove_rss: "删除新闻提要时出错",
        Error_add_rss: "添加新闻提要时出错",
        Error_save_rss: "保存新闻提要时出错",
        Rss_updating: "RSS 更新",
        Rss_removing: "RSS 去除",
        //---RSS

        //+++Lang
        russian: "俄语",
        english: "英语",
        german: "德语",
        chinese: "中国",
        Russian: "俄语",
        English: "英语",
        German: "德语",
        Chinese: "中国",
        ru: "俄语",
        en: "英语",
        de: "德语",
        zh: "中国",
        Error_load_langs: "加载语言错误",
        Error_remove_lang: "删除语言错误",
        Error_add_lang: "添加语言错误",

        Min_one_lang_must_be_set: "至少需要一种语言",
        Langs_loading: "语言被加载",
        Langs_adding: "添加语言",
        Langs_removing: "删除语言",
        UI_Language: "界面语言",
        Select_User_Interface_Language: "选择界面语言",
        Show_content_language_switcher_on_frontend: "显示网站上的语言切换",
        Content_Languages: "内容语言",
        All_Languages: "所有语言",
        Find_by: "以什么途径查找",
        By_email: "通过电子邮件",
        By_first_name: "按名称",
        By_middle_name: "用父称",
        By_last_name: "按姓氏",
        By_nick: "用别名 ",
        By_phone: "用电话",
        By_site: "用网站",
        //---Lang

        //+++Users
        Privilege: "特权",
        User_privelege: "用户权限",
        Users_privelege: "用户权限",
        User_edit: "编辑用户",
        User_remove: "删除用户",
        Back_to_user_list: "返回用户列表",
        Files_management: "使用文件",
        Admin_access: "管理员权限",
        Category_Write: "记录类别",
        Category_Read: "阅读分类",
        Users_Write: "用户记录",
        Users_Read: "用户阅读",
        Posts_Write: "发布帖子",
        Posts_Read: "阅读帖子",
        Priv_Blocked: "锁定",
        User_add: "添加用户",
        Back_to_users: "返回用户列表",
        Users_loading: "用户正在加载",

        Error_load_users: "下载用户错误",
        Error_block_users: "用户锁定错误",
        Error_remove_users: "删除用户错误",
        Error_save_privs: "保存权限错误",
        Error_add_user: "添加用户错误",
        Error_save_user: "保存用户错误",
        //---Users

        //+++Settings
        KEYWORDS: "关键字",
        LANGS_SHOW_SWITCHER: "在网站上选择语言面板",
        LOGIN_SWITCHER: "网站上的授权小组",
        REGISTRATION_SWITCHER: "网站注册小组",
        SITE_TITLE: "网站名称",
        DESCRIPTION: "网站描述",
        ANONYMOUS_ACCESS: "未经授权的用户访问",
        SHOW_POST_DATE: "显示发布发布日期",
        COMMENTS_ENABLE: "评论",
        ANONYMOUS_COMMENTS: "未经授权的用户可以发表评论",
        RECAPCHA_COMMENTS: "验证码以发表评论",
        CATEGORIES_ENABLE: "类别",
        CATEGORIES_TREE_LPANEL: "类别输出树",
        RSS_ENABLE: "通讯",
        RECAPCHA_PUBLIC_KEY: "RECAPCHA 公钥",
        RECAPCHA_PRIVATE_KEY: "RECAPCHA 私钥",
        Reset: "复位",

        Setting_reset_success: "设置成功重置",
        Setting_save_success: "设置成功保存",
        Error_save_settings: "保存设置错误",
        Error_load_settings: "加载设置错误",
        //---Settings

        To_reset_pass_lnk_sent: "重置密码，链接已发送到您的电子邮件",
        Error_category_moving: "错误移动类别",
        Comments_delete_success: "评论成功删除",
        Comments_save_success: "已成功保存评论",
        Language_delete_success: "语言被成功删除",
        Language_added_success: "语言成功添加",
        Rss_delete_success: "磁带被成功删除",
        Rss_added_success: "磁带已成功添加",
        Rss_saved_success: "磁带已成功保存",
        Users_delete_success: "用户成功删除",
        Privelege_set_success: "特权成功安装",
        Users_added_success: "用户成功添加",
        User_saved_success: "用户成功保存",

        Users_privelege_set: "已成功安装权限",
        User_saving: "保存用户",
        Users_loading: "上传用户",
        Users_blocking: "阻止用户",
        User_adding: "添加用户",
        User_removing: "删除用户"
    }
};
