<!DOCTYPE html>
<html>
<head>
    <link rel=icon href=/admin/favicon.ico type=image/x-icon>
    <meta charset=utf-8>
    <title>vuepress</title>
    <link href=/admin/css/app.css rel=stylesheet>
</head>
<body>
    <div id=app></div>
    <script type=text/javascript src=/admin/js/manifest.js></script>
    <script type=text/javascript src=/admin/js/vendor.js></script>
    <script type=text/javascript src=/admin/js/app.js></script>
</body>
</html>
