<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>
            Installed
        </title>
    </head>
    <body style="width:100%;padding-left:50%;overflow-x:hidden;">
        <div style="width:250px;margin-left:-125px;text-align:center;">
            <?php 
                //echo $tmp; 
            ?>
            <h3>Vuepress configured.</h3>
            <h3>Now you can go to auth page<br><br><a href="/auth">&gt;&gt;&gt; Authentication &lt;&lt;&lt;</a></h3>
        </div>
    </body>
</html>
