<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>
            Mysql configuration error
        </title>
    </head>
    <body style="width:100%;padding-left:50%;overflow-x:hidden;">
        <div style="width:250px;margin-left:-125px;text-align:center;">
            <h3>Mysql configuration error</h3>
            <h3>Go to install page<br><br><a href="/installredirect">&gt;&gt;&gt; Install again &lt;&lt;&lt;</a></h3>
        </div>
    </body>
</html>
